---
- name: Pull and Run docker image of jeetkanakhara/spe-calculator
  hosts: all
  tasks:
    - name: Pull jeetkanakhara/spe-calculator
      docker_image:
        name: jeetkanakhara/spe-calculator
        source: pull



